inputs:
  port:
    description: 'Specify port for node application to run'
    default: 1010
  env:
    description: 'Environment for sample node application'
    default: 'dev'
runs:
  using: "composite"
  steps: 
    - name: Print output
      run: Deploying into ${{ inputs.env }}
      shell: bash
    - name: Delete service
      working-directory: working-dir
      run : pm2 delete greetings-app-${{ inputs.env }} || set "ErrorLevel=0"
      shell: bash
    - name: Start service
      working-directory: working-dir
      run : pm2 start app.py --name greetings-app-${{ inputs.env }} -- --port ${{ inputs.port }}
      shell: bash
